Simple interface
tutu-ru/php-config pull request #5
Opened 2019-01-10 12:35 UTC by todoshcenko

2019-01-10 14:13 UTC, alexkrass commented on src/ConfigContainer.php
> +    public function __construct($mergeArrayValues = true)
mergeArrayValues появился,
сразу вопросы будут - о чём этот параметр - может в доке написать про него ?
всё таки основной класс библиотеки

2019-01-10 14:16 UTC, alexkrass commented on src/ConfigContainer.php
> +    public function __construct($mergeArrayValues = true)
и вопрос - почему именно true тут по дефолту ?
по коду вроде проще выглядит использование getSimpleValue

2019-01-10 14:18 UTC, alexkrass requested changes
мелкие вопросы

2019-01-10 14:38 UTC, alexkrass commented
договорились
 - убрать конструктор из контейнера
 - убрать механизм мержа из библиотеки
 - поднять JsonConfig из тестов в src

2019-01-11 00:00 UTC, todoshcenko commented on src/ConfigContainer.php
> +    public function __construct($mergeArrayValues = true)
Удалено

2019-01-11 07:24 UTC, alexkrass commented
еще вопрос про EnvironmentUtils
сейчас это неиспользуемый в коде библиотеке класс и про него нет ни слова в документации
может что-то написать про него ?

2019-01-11 08:20 UTC, alexkrass commented
понял, напиши тогда коммент в классе и заапрувлю

2019-01-11 08:59 UTC, artemseleznev commented on src/JsonConfig/JsonConfig.php
> +class JsonConfig implements ConfigInterface
получается, что этот класс не Mutable, но у него есть возможность изменить конфиг через setConfigData. То же самое с EtcdConfig. Как сделать это красиво и без дублирования, и стоит ли - решай сам

2019-01-11 08:59 UTC, artemseleznev commented on tests/BaseTest.php
> +    protected function createMutableConfig(string $filename, bool $mock = false): MutableJsonConfig
тогда уже "createMutableJsonConfig" для порядка?

2019-01-11 09:09 UTC, todoshcenko commented on src/JsonConfig/JsonConfig.php
> +class JsonConfig implements ConfigInterface
У клиентов нет такой возможности. Это не публичные методы

2019-01-11 09:32 UTC, todoshcenko commented on tests/BaseTest.php
> +    protected function createMutableConfig(string $filename, bool $mock = false): MutableJsonConfig
переименовал

2019-01-11 13:06 UTC, artemseleznev approved these changes

2019-01-11 13:47 UTC, alexkrass approved these changes

2019-01-11 14:10 UTC, merged